config/routes.rb
Dyr::Application.routes.draw do
  
  get "conform/index"

  resources :posts
  if Rails.env.staging? || Rails.env.development?
    controller :mobile_api do
      
      get "addcoments"
      get "addfavourite"
      get "addmemoriedetails"
      get "B"
      get "GetMemories"
      get "comments"
      get "followuser"
      get "getcategories"
      get "getcomments"
      get "getshowdown"
      get "getuserdetails"
      get "rememberedmemories"
      get "result"
      get "search"
      get "signin"
      get "views"
      get "usercomments"
      get "userfollowedby"
      get "userfollowing"
      get "userrememberedmemories"
      get "emailconform"
      get "index"
      get "conform"
      post "conform"
    end
  end
  
  get "banned/index"
  get "whotofollow/index"

  get "images/destroy"
  get "list/index"

  controller :feeds do
    get "feeds/index"
    get "feeds/next"
    
  end

  resources :categories
  
  resources :votes
  
  resources :visits, :only => :create, :method => :post

  root :to => "home#index"
  controller :home do
    match 'list_view', :via => [:get, :post], :path => "/listing-memories"
    match 'vip', :via => :get, :path => '/VIP_ENTRANCE'
    match 'vip', :via => :get, :path => '/VIP_entrance'
    match 'vip', :via => :get, :path => '/vip_ENTRANCE'
    match 'vip', :via => :get, :path => '/vip_entrance'
    match 'vip', :via => :get, :path => '/preview'
    match 'decade_index', :via => :get
    match 'entrance', :via => [:get, :put]
    match 'birthyear', :via => [:get, :put]
    match 'splash'
    match 'help'
    match 'about'
    match 'terms_of_service'
    match 'privacy_policy'
    match 'get_our_app'
    match 'login_register'
    match 'trending'
    match 'contact_us'
  end
  
  resources :showdowns
  match "/voting/next_vote" => "showdowns#next_vote", :via => :get
  
  
  devise_for :images, :controllers => { :images => "images", :memories => "memories" }, :sign_out_via => [:post, :delete, :get]
  namespace :images do
    match 'edit/:id', :action => :edit, :as => 'edit_images'
    match ':memory_id/:id', :action => :destroy, :as => 'delete_by_images_memory_id'
  end

  devise_for :users, :controllers => { :registrations => "registrations", :passwords => 'passwords', :sessions => 'sessions', :confirmations => "confirmations"}, :sign_out_via => [:post, :delete, :get]
  namespace :users do
    post 'follow'
    match 'unfollow/:followee_id', :action => :unfollow, :as => 'unfollow'
    match 'home'
    match ':id/profile', :action => :profile, :as => 'profile'    
    match 'follow_from_profile/:followee_id', :action => :follow_from_profile, :as => 'follow_from_profile'
    match 'unfollow_from_profile/:followee_id', :action => :unfollow_from_profile, :as => 'unfollow_from_profile'
    match 'follow_from_profile_followers/:followee_id', :action => :follow_from_profile_followers, :as => 'follow_from_profile_followers'
    match 'unfollow_from_profile_followers/:followee_id', :action => :unfollow_from_profile_followers, :as => 'unfollow_from_profile_followers'
    match 'bu/:id', :action => 'become_user', :as => 'b' #convenience method to circumvent FB logins, should never be called by the public
    match 'set_notification/:notification_bit/:new_state', :action => :set_notification, :as => :set_notification
    match 'set_preference/:notification_bit/:new_state', :action => :set_preference, :as => :set_preference
  end
  
  match '/auth/:service/callback' => 'services#create' 
  resources :services, :only => [:index, :create, :destroy]
  
  match '/memories/add-to-memory-bank' => 'memories#add_to_memory_bank', :as => 'add_to_memory_bank'
  match '/memories/my-memory-bank' => 'memories#memory_bank', :as => 'memory_bank'
  match '/memories/:id/send_to_a_friend' => 'memories#send_to_a_friend', :as => 'send_to_a_friend'
  match '/memories/categories/:category_id' => 'memories#per_category', :as => 'memories_per_category'
  match '/memories/decades/:decade_id' => 'memories#per_decade', :as => 'memories_per_decade'
  match '/memories/my-suggested-memories' => 'memories#per_similar_demographics', :as => 'memories_per_similar_demographics'
  match '/memories/birthyear-suggested-memories' => 'memories#by_birthyear', :as => 'by_birthyear'
  resources :memories do
    member do
      match 'also_remembers'
      match 'forgot'
      match 'suspend'
      match 'unsuspend'
      match 'ban_user'
      match 'unban_user'
    end
  end
  
  resources :previews, :only => [] do
    member do
      get 'comments'
      get 'related'
      get 'remembered'
      get 'photos'
      get 'post_comment'
      get 'also_remembers'
      get 'forgot'
      get 'follow'
      get 'unfollow'
      get 'delete'
    end
  end
  
  resources :images, :only => [:create, :update, :destroy]
  
  match '/search' => 'search#new'
  match '/search/result' => 'search#result'
  match '/whotofollow/index' => 'whotofollow#index'
  match '/images/memory_id/id' => 'images/:memory_id#:id'

  resources :comments, :only => :create
 
  namespace :v1 do
    controller :lists do
      match 'categories'
      match 'decades'
    end
    controller :memories do
      match 'memories/:start/:amount', :action => :index
      match 'memories/:start/:amount/decade/:id', :action => :per_decade
      match 'memories/:start/:amount/category/:id', :action => :per_category
      match 'memories/:start/:amount/suggested/:year/:gender', :action => :suggested
      match 'memories/:start/:amount/suggested/:year', :action => :suggested
    end
  end
  
  resources :invitations, :only => [:new, :create]











end

app/views/shared/_categories_and_decades.haml
.categories
  .top_categories
    %span.normal Select: Category or Decade
    .remove.hide_category_list x
    -# %span.normal.hide_category_list Hide
  .left_list
    %span.or OR
    %ul.categories_list
      %li
        %span.cat
          = link_to "All", root_path
        %span.num
          = Memory.count
      - Category.menu_items.each do |cat_arr|
        %li
          %span.cat
            %a{:href => memories_per_category_path(cat_arr[0])}
              #{cat_arr[1].titleize}
          %span.num
            = cat_arr[2]
  .right_list
    %ul.years_list
      - Memory::DECADES.sort.each do |arr|
        %li
          %span.year
            %a{:href=>"#{memories_per_decade_path(arr[0])}"}
              = arr[1]
          %span.num
            #{Memory.where(:decade => arr[0]).count}

app/views/shared/_category_selector.haml
#category_selector
  - if @categories
    %a#category_header{:href => '#'}
      -if @category
        = @category.name.titleize
      -else
        Select a category...
    #category_box
      - @categories.each do |c|
        -if c.memories.any?
          -if params[:category] && (params[:category].to_i == c.id)
            =link_to dyr_categories_title(c.name), '#', :class => 'current', :id => "category_#{c.id}"
          -else
            =link_to dyr_categories_title(c.name), root_path(:category => c.id, :decade => params[:decade]), :id => "category_#{c.id}"
      - if !params[:category]
        =link_to 'All Categories', '#', :class => 'current'
      - else
        =link_to "All Categories", root_path(:decade => params[:decade])

app/views/shared/_decade_selector.haml
#decade_wrapper
  #decade_timeline
    #decade_line
    -Memory::DECADES.sort.each do |d|
      -if params[:decade] && (params[:decade].to_i == d[0])
        =link_to d[1], root_path(:category => params[:category], :decade => d[0]), :id => "decade_#{d[0]}", :class => 'current decade', :data_id => d[0]
      -else
        =link_to d[1], root_path(:category => params[:category], :decade => d[0]), :id => "decade_#{d[0]}", :class => 'decade', :data_id => d[0]
    -if !params[:decade]
      =link_to "all", '#', :id => 'decade_all', :class => 'current', :data_id => '0'
    -else
      =link_to "all", root_path(:category => params[:category]), :id => 'decade_all', :data_id => '0'

app/views/shared/_header.haml
#wrapper_header
  #header
    #do-you-remember-logo
      = link_to image_tag("doYouRememberLogo.png"), root_path
    #header_right
      %a#search_menu_head.menu_head{:data_id => "search_menu"} 
        Search
      %a#view_menu_head.menu_head{:data_id => "view_menu"} 
        View
      %a#year_menu_head.menu_head{:data_id => "year_menu"} 
        Decade
        %span#year_hook.status_hook
      %a#tag_menu_head.menu_head{:data_id => "tag_menu"} 
        Category
        %span#tag_hook.status_hook
      - if user_signed_in?
        = link_to "Add", new_memory_path, :id => "add_menu_head", :data_id => "add_menu" , :class => "menu_head sign_in"
      - else
        = link_to "Add", new_user_session_path, :class => "menu_head sign_in"
      %a#more_menu_head.menu_head{:data_id => "more_menu"} 
        More
      - if current_user
        = link_to image_tag(current_user.my_profile_image), users_home_path, :id => "user_menu_head", :class => "menu_head user_menu_hook", :data_id => "user_menu"
      - else
        =link_to 'Sign&nbsp;In'.html_safe, new_user_session_path, :id => "user_menu_head", :class => "menu_head sign_in"
  - if current_user
    #user_menu.dropdown_menu
      #dropdown_caret
      #user_name_header=current_user.name
      #user_menu_items
        - if  current_user.try(:admin?)
          =link_to "Categories", categories_path, :class => 'user_menu_item admin_menu_item'
          =link_to "Showdowns", showdowns_path, :class => 'user_menu_item admin_menu_item'

        =link_to "My Account", users_home_path, :class => 'user_menu_item'
        =link_to "Memory Bank", memory_bank_path, :class => 'user_menu_item'
        =link_to "Suggested Memories", memories_per_similar_demographics_path, :class => 'user_menu_item'
        =link_to "Invite Friends", new_invitation_path, :class => 'user_menu_item'
        =link_to "Who to Follow", whotofollow_index_path, :class => 'user_menu_item'
        =link_to "Sign Out", '/users/sign_out', :class => 'user_menu_item', :id => 'sign_out_menu_item'
  #popdown_menus
    #search_menu.header_menu
      = form_tag search_result_path do
        = text_field_tag 'search[term]', '', :placeholder => 'search...', :maxlength => 60, :spellcheck => true
        = submit_tag "Search", :id => 'search_btn'
      = button_to "Advanced Search...", :id => 'advanced_search'
    #view_menu.header_memu
      = link_to "Mosaic", root_path
      \| 
      = link_to "Polaroid", nil
      \| 
      = link_to "List", list_view_path
    #year_menu.header_menu
      =render "shared/decade_selector"
    #tag_menu.header_menu
      =render "shared/tag_selector"
    -# Add creates a lightbox, not a menu
    #more_menu.header_menu
      =link_to 'Blog', "http://blog.doyouremember.com", :class => 'more_menu_item', :target => "blank"
      =link_to 'About Us', about_path,:class => 'more_menu_item'
      =link_to 'Contact', contact_us_path,:class => 'more_menu_item'
      =link_to 'Help', help_path,:class => 'more_menu_item'
      =link_to 'Legal', terms_of_service_path,:class => 'more_menu_item'
      =link_to 'Get the App', get_our_app_path,:class => 'more_menu_item'

app/views/shared/_memory_bank_slider.haml
#memoryBankSliderContainer
  - if @my_memory_bank
    - if @my_memory_bank.count >= 1
      %ul#memoryBankSlider
        - @my_memory_bank.each_slice(11) do |memory_group|
          %li.memoryBankSliderSection
            - memory_group.each do |memory|
              .memoryBankSlider.ui-widget-content
                .image
                  %a{:href => "#{memory_path(memory)}"}
                    = image_tag(memory.images.first.this_url(:medium), :title => dyr_title(memory.name), :class => "memoryOnMyBank")
  - else
    %ul#memoryBankSlider
      %li.memoryBankSliderSection
        .memoryBankSlider
          #memoryBankInfo
            %h5 Drag memories here to fill your memory bank.
            .extraInfo 
              Go to your 
              \ 
              = link_to "Memory Bank", memory_bank_path
              \ 
              to see all of your saved memories.

app/views/shared/_memory_row.haml
- highlight_terms = !@search.nil? && @search.params.has_key?(:term) && !@search.params[:term].blank?
%tr{:class => cycle('odd','even'), :id => 'memory-' + m.to_param}
  %td.img
    - if m.images.count > 0
      %img{:src => m.images.first.this_url(:thumb)}
  %td.name
    - if highlight_terms
      = link_to highlight(m.name, @search.term_filtered), memory_path(m)
    - else
      = link_to m.name, memory_path(m)
    - if current_user && current_user.eql?(m.user)
      = link_to 'Edit', edit_memory_path(m)
  %td.description
    - if highlight_terms
      = highlight(m.description[0..45], @search.term_filtered)
    - else
      = m.description[0..45]
    - if m.description.length > 45
      \...
      %br
      = link_to('more', memory_path(m))
    .spacer
  %td.categories=raw m.categories.sort.collect(&:name).join('<br />')
  %td.created= m.created_at.strftime("%B %e, %Y")
  %td.more= button_to 'more', memory_path(m), :method => :get

app/views/shared/_not_logged_in.haml
#welcome-to-do-you-remember
  / .remove.hide_welcome_message x
  / %h1 &nbsp;&nbsp;&nbsp;Welcome to DoYouRemember?... The Social Memories site.
  / %h2 
  /   
  / %p 
  /   As a guest, you can see what others have posted. 
  /   %a{:href => login_register_path}="LOGIN" 
  /   to post your own memories, add comments or photos and create a Memory Bank. 
  / 
  / %p
  /   To save a memory posted by others, “light” the elephant to yellow. To follow users with similar memories, click the circle to blue.
  / 
  / %p
  /   The red “PUSH” button at the bottom of each memory box opens a quick-view of comments, people who also remember that memory, similar items you might remember and more.  
  / %p  
  /   If you need further assistance INFO will provide answers to your questions or feel free to email us at info@doyouremember.com.  
  / %p  
  /   Please don't forget to send feedback to help us improve DoYouRemember.  Thank you.
  /   -#%a{:href => "http://www.apple.com/iphone/from-the-app-store/"}= "download our app" + "."
  .remove.hide_welcome_message x
  %p 
    Welcome to DoYouRemember, the site to post & share memories.  Navigate the buttons above to see memories by category, all or trending.  Use the one-step 
    =# link_to "LOGIN", "/auth/facebook"
    = link_to "LOGIN", new_user_session_path
    \ to begin creating your own memories and to see memories we think you might like.  We're in beta, and appreciate feedback.
    = mail_to "info@doyouremember.com", "<b>CLICK HERE</b>".html_safe, :subject => "Feedback for doyouremember.com", :encode => "javascript"
    to provide suggestions or just to say hi.
    %em 
      = link_to "INFO", help_path
    \ tab above will provide additional answers if you need them. Thank you. 

app/views/shared/_order_by_and_categories.haml
.menu_left
  %span.white Sort by:
  %a{:id => 'view_most_popular', :href => '#', :class => 'current yellow', :title => 'See what people are talking about'} Trending 
  -# %a{:id => 'view_latest', :href => '#', :class => 'yellow', :title => 'See what memories have recently been added'} New
.menu_right
  %span.white Category:
  %span.yellow= (@category.nil? ? 'All' : @category.name)
  %span.yellow [
  -# %a.blue{:id => 'choose_category', :href => '#'} Choose Category
  %span.yellow ]

app/views/shared/_search.haml
.search_box
  .iso_img
  .search_form
    = form_tag search_result_path do
      = text_field_tag 'search[term]', '', :class => 'validate_five_txt', :value => 'Enter your memory here - 5 word maximum'
      = submit_tag '', :class => 'validate_five_btn'

app/views/shared/_showdown_countdown.html.haml
#autoLoadingShowdown
  .info
    Next game in 
  .showdownCountDown
    10
-##autoLoadingShowdownPaused.hidden
  .info
    PAUSED

app/views/shared/_slider.html.haml
- unless @slider_memories.count >= 1
  #spacer
    %br/
- else
  #sliderContainer
    %ul#memorySlider
      - @slider_memories.each_slice(8) do |memory1,memory2,memory3,memory4,memory5,memory6,memory7,memory8|
        %li.memorySliderContainer
          - if memory1
            .memorySlider
              .image
                %a{:href => "#{memory_path(memory1)}"}
                  = image_tag(memory1.images.first.this_url(:medium), :title => dyr_title(memory1.name))
              %div{:class => "caption-bottom"}
                = link_to truncate(memory1.category.name.titleize, :length => 15), memories_per_category_path(memory1.category)
          - if memory2
            .memorySlider
              .image
                %a{:href => "#{memory_path(memory2)}"}
                  = image_tag(memory2.images.first.this_url(:medium), :title => dyr_title(memory2.name))
              %div{:class => "caption-bottom"}
                = link_to truncate(memory2.category.name.titleize, :length => 15), memories_per_category_path(memory2.category)
          - if memory3
            .memorySlider
              .image
                %a{:href => "#{memory_path(memory3)}"}
                  = image_tag(memory3.images.first.this_url(:medium), :title => dyr_title(memory3.name))
              %div{:class => "caption-bottom"}
                = link_to truncate(memory3.category.name.titleize, :length => 15), memories_per_category_path(memory3.category)
          - if memory4
            .memorySlider
              .image
                %a{:href => "#{memory_path(memory4)}"}
                  = image_tag(memory4.images.first.this_url(:medium), :title => dyr_title(memory4.name))
              %div{:class => "caption-bottom"}
                = link_to truncate(memory4.category.name.titleize, :length => 15), memories_per_category_path(memory4.category)
          - if memory5
            .memorySlider
              .image
                %a{:href => "#{memory_path(memory5)}"}
                  = image_tag(memory5.images.first.this_url(:medium), :title => dyr_title(memory5.name))
              %div{:class => "caption-bottom"}
                = link_to truncate(memory5.category.name.titleize, :length => 15), memories_per_category_path(memory5.category)
          - if memory6
            .memorySlider
              .image
                %a{:href => "#{memory_path(memory6)}"}
                  = image_tag(memory6.images.first.this_url(:medium), :title => dyr_title(memory6.name))
              %div{:class => "caption-bottom"}
                = link_to truncate(memory6.category.name.titleize, :length => 15), memories_per_category_path(memory6.category)
          - if memory7
            .memorySlider
              .image
                %a{:href => "#{memory_path(memory7)}"}
                  = image_tag(memory7.images.first.this_url(:medium), :title => dyr_title(memory7.name))
              %div{:class => "caption-bottom"}
                = link_to truncate(memory7.category.name.titleize, :length => 15), memories_per_category_path(memory7.category)
          - if memory8
            .memorySlider
              .image
                %a{:href => "#{memory_path(memory8)}"}
                  = image_tag(memory8.images.first.this_url(:medium), :title => dyr_title(memory8.name))
              %div{:class => "caption-bottom"}
                = link_to truncate(memory8.category.name.titleize, :length => 15), memories_per_category_path(memory8.category)

app/views/shared/_tag_selector.haml
#tag_box
  -if @categories
    - @categories.each do |c|
      -if c.memories.any?
        -if params[:category] && (params[:category].to_i == c.id)
          =link_to dyr_categories_title(c.name) + " (#{c.memories.count})", '#', :class => 'current tag', :id => "category_#{c.id}"
        -else
          =link_to dyr_categories_title(c.name) + " (#{c.memories.count})", root_path(:category => c.id, :decade => params[:decade]),:class => 'tag', :id => "category_#{c.id}"
    - if !params[:category]
      =link_to "All Categories (#{Memory.count})", '#', :class => 'current'
    - else
      =link_to "All Categories (#{Memory.count})", root_path(:decade => params[:decade])

app/views/shared/ori_header.haml
#wrapper_header
  #header
    .first_row
      .cont
        %a.iso{:href => '/', :title => 'Home'}
          %img{:src => "#{asset_path 'iso_header.png'}", :border => 0}
        %a.logo{:href => '/', :title => 'Home'}
          %img{:src => "#{asset_path 'logo_header.png'}", :border => 0}
        .search_header
          = form_tag search_result_path do
            = text_field_tag 'search[term]', '', :placeholder => 'Enter your search here', :maxlength => 60, :spellcheck => true
            = submit_tag '', :id => 'search_btn'
        .add_memory_header
          = form_tag new_memory_path, :method => :get do
            = text_field_tag 'name', '', :placeholder => 'Submit a memory', :maxlength => 60, :spellcheck => true
            = submit_tag '', :id => 'add_memory_btn'
        .top_header_user
          %a.btn_header.info{:href => "#", :title => 'Info'}
            %img{:src => "#{asset_path 'about.png'}", :border => 0}
          %a.btn_header#submit_memory_lnk{:href => "#{new_memory_path}", :title => 'Submit a memory'}
            %img{:src => "#{asset_path 'submit.png'}", :title => 'Submit a memory', :border => 0}
          %a.btn_header{:href => "#{new_invitation_path}", :title => 'Invite friends'}
            %img{:src => "#{asset_path 'invite.png', :title => 'Invite friends'}", :border => 0}
            
          .nav_about_user{:style => 'display:none'}
            %a{:href => about_path}
              About
            %a{:href => terms_of_service_path}
              Terms of Service
            %a{:href => privacy_policy_path}
              Privacy Policy
            %a{:href => get_our_app_path}
              Get our App
              
        .user_menu
          - if current_user
            .cont_user_menu
              %a{:href => '#'}
                = image_tag current_user.my_profile_image, :size => '25x25'
                %span.ico_btn
                  = current_user.name
              .nav_user{:style => 'display:none'}
                .box_nav_user
                  %span.f
                    %a.last{:href => users_home_path} My DYR
                  %span.s
                    %a.last.right{:href => '/users/sign_out'}= 'Log out' 
            - else
              %a.last{:href => login_register_path}= 'Login or Register'
    -#.second_row
      .cont
        %ul#main_menu
          - if current_user
            %li.users_home
              %a.btn.menu{:href => "#{users_home_path}"}
                %img{:src => "#{asset_path 'iso_btn.png'}", :border => 0}
                %span MY DYR
          %li
            %a.btn.menu{:href => "#", :class => "search_btn"}
              %img{:src => "#{asset_path 'search_btn.png'}", :border => 0}
              %span search
          %li.memories_new
            %a.btn.menu{:href => "#{new_memory_path}"}
              %img{:src => "#{asset_path 'submit_btn.png'}", :border => 0}
              %span submit
          %li
            %a.btn.menu{:href => "#"}
              %img{:src => "#{asset_path 'invite_btn.png'}", :border => 0}
              %span invite
          %li
            %a.btn.menu{:href => "#"}
              %img{:src => "#{asset_path 'showdown_btn.png'}", :border => 0}
              %span showdown
          %li
            %a.btn.menu{:href => "#"}
              %img{:src => "#{asset_path 'shop_btn.png'}", :border => 0}
              %span shop
          %li
            %a.btn.menu{:href => "#"}
              %img{:src => "#{asset_path 'blog_btn.png'}", :border => 0}
              %span blog

app/views/shared/popup.haml
#signInUpBox
  #xGoBack
    %a.Cancel{:href => "#"} x
  #DYRlogo
    = image_tag "doYouRememberSmallLogo.png", :title => "Do Your Remember?"
  .loginUsingSocialNetworks
    = link_to image_tag("facebook_login_bar.png", :title => "Login Using Your Facebook Account"), '/auth/facebook', :class => "social"
    = link_to image_tag("twitter_login_bar.png", :title => "Login Using Your Twitter Account"), '/auth/twitter', :class => "social"
  #loginManually
    = form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f|
      .field
        = f.email_field :email, :placeholder => "Login with Email"
      .field
        = f.password_field :password, :placeholder => "Password"
      .field
        = f.submit "Sign in", :class => "greyButton"
        .right
          = link_to "Forgot password?", new_password_path(resource_name)

  .clear
  #signUpLink
    Sign Up with Email
    = link_to "Click Here", new_registration_path(resource_name)