config/routes.rb
Dyr::Application.routes.draw do
  
  get "conform/index"

  resources :posts
  if Rails.env.staging? || Rails.env.development?
    controller :mobile_api do
      
      get "addcoments"
      get "addfavourite"
      get "addmemoriedetails"
      get "B"
      get "GetMemories"
      get "comments"
      get "followuser"
      get "getcategories"
      get "getcomments"
      get "getshowdown"
      get "getuserdetails"
      get "rememberedmemories"
      get "result"
      get "search"
      get "signin"
      get "views"
      get "usercomments"
      get "userfollowedby"
      get "userfollowing"
      get "userrememberedmemories"
      get "emailconform"
      get "index"
      get "conform"
      post "conform"
    end
  end
  
  get "banned/index"
  get "whotofollow/index"

  get "images/destroy"
  get "list/index"

  controller :feeds do
    get "feeds/index"
    get "feeds/next"
    
  end

  resources :categories
  
  resources :votes
  
  resources :visits, :only => :create, :method => :post

  root :to => "home#index"
  controller :home do
    match 'list_view', :via => [:get, :post], :path => "/listing-memories"
    match 'vip', :via => :get, :path => '/VIP_ENTRANCE'
    match 'vip', :via => :get, :path => '/VIP_entrance'
    match 'vip', :via => :get, :path => '/vip_ENTRANCE'
    match 'vip', :via => :get, :path => '/vip_entrance'
    match 'vip', :via => :get, :path => '/preview'
    match 'decade_index', :via => :get
    match 'entrance', :via => [:get, :put]
    match 'birthyear', :via => [:get, :put]
    match 'splash'
    match 'help'
    match 'about'
    match 'terms_of_service'
    match 'privacy_policy'
    match 'get_our_app'
    match 'login_register'
    match 'trending'
    match 'contact_us'
  end
  
  resources :showdowns
  match "/voting/next_vote" => "showdowns#next_vote", :via => :get
  
  
  devise_for :images, :controllers => { :images => "images", :memories => "memories" }, :sign_out_via => [:post, :delete, :get]
  namespace :images do
    match 'edit/:id', :action => :edit, :as => 'edit_images'
    match ':memory_id/:id', :action => :destroy, :as => 'delete_by_images_memory_id'
  end

  devise_for :users, :controllers => { :registrations => "registrations", :passwords => 'passwords', :sessions => 'sessions', :confirmations => "confirmations"}, :sign_out_via => [:post, :delete, :get]
  namespace :users do
    post 'follow'
    match 'unfollow/:followee_id', :action => :unfollow, :as => 'unfollow'
    match 'home'
    match ':id/profile', :action => :profile, :as => 'profile'    
    match 'follow_from_profile/:followee_id', :action => :follow_from_profile, :as => 'follow_from_profile'
    match 'unfollow_from_profile/:followee_id', :action => :unfollow_from_profile, :as => 'unfollow_from_profile'
    match 'follow_from_profile_followers/:followee_id', :action => :follow_from_profile_followers, :as => 'follow_from_profile_followers'
    match 'unfollow_from_profile_followers/:followee_id', :action => :unfollow_from_profile_followers, :as => 'unfollow_from_profile_followers'
    match 'bu/:id', :action => 'become_user', :as => 'b' #convenience method to circumvent FB logins, should never be called by the public
    match 'set_notification/:notification_bit/:new_state', :action => :set_notification, :as => :set_notification
    match 'set_preference/:notification_bit/:new_state', :action => :set_preference, :as => :set_preference
  end
  
  match '/auth/:service/callback' => 'services#create' 
  resources :services, :only => [:index, :create, :destroy]
  
  match '/memories/add-to-memory-bank' => 'memories#add_to_memory_bank', :as => 'add_to_memory_bank'
  match '/memories/my-memory-bank' => 'memories#memory_bank', :as => 'memory_bank'
  match '/memories/:id/send_to_a_friend' => 'memories#send_to_a_friend', :as => 'send_to_a_friend'
  match '/memories/categories/:category_id' => 'memories#per_category', :as => 'memories_per_category'
  match '/memories/decades/:decade_id' => 'memories#per_decade', :as => 'memories_per_decade'
  match '/memories/my-suggested-memories' => 'memories#per_similar_demographics', :as => 'memories_per_similar_demographics'
  match '/memories/birthyear-suggested-memories' => 'memories#by_birthyear', :as => 'by_birthyear'
  resources :memories do
    member do
      match 'also_remembers'
      match 'forgot'
      match 'suspend'
      match 'unsuspend'
      match 'ban_user'
      match 'unban_user'
    end
  end
  
  resources :previews, :only => [] do
    member do
      get 'comments'
      get 'related'
      get 'remembered'
      get 'photos'
      get 'post_comment'
      get 'also_remembers'
      get 'forgot'
      get 'follow'
      get 'unfollow'
      get 'delete'
    end
  end
  
  resources :images, :only => [:create, :update, :destroy]
  
  match '/search' => 'search#new'
  match '/search/result' => 'search#result'
  match '/whotofollow/index' => 'whotofollow#index'
  match '/images/memory_id/id' => 'images/:memory_id#:id'

  resources :comments, :only => :create
 
  namespace :v1 do
    controller :lists do
      match 'categories'
      match 'decades'
    end
    controller :memories do
      match 'memories/:start/:amount', :action => :index
      match 'memories/:start/:amount/decade/:id', :action => :per_decade
      match 'memories/:start/:amount/category/:id', :action => :per_category
      match 'memories/:start/:amount/suggested/:year/:gender', :action => :suggested
      match 'memories/:start/:amount/suggested/:year', :action => :suggested
    end
  end
  
  resources :invitations, :only => [:new, :create]











end

app/controllers/home_controller.rb
class HomeController < ApplicationController  
  before_filter :splash_user, :only => :index
  

  # def decade_index
  #   # @memories = Memory.has_images.order("created_at DESC")#.page(params[:page]).per(100)
  #   @memories ||= Memory.scoped.has_images.order("created_at DESC").page(params[:page]).per(100)
  #   @categories = Category.all
  #   if params[:decade]
  #     decade = @memories.where(:decade => params[:decade])
  #     @decade = decade.page(params[:page]).per(100)
  #   else
  #     @decade = @memories.page(params[:page]).per(100)
  #   end
  #   # @memories = Memory.scoped.has_images.order("created_at DESC").page(params[:page]).per(100)
   
  #   respond_to do |format|
  #       format.html # index.html.erb
  #       format.js  { render :layout => false }
  #   end

  # end


  def index
    # original, unfiltered query: 
    # @memories = Memory.has_images.order("created_at DESC").page(params[:page]).per(CONFIG[:custom_per_page])
    @all_memories ||= Memory.has_images.order("created_at DESC").limit(200)
    
    #Switching off since its not being used at now
    #@feeds = Memory.scoped(:order => "RAND()").has_images.page(params[:feed]).per(5)

    #too bad i couldn't chain this all into one mega-query...
    ## this instances were working
    #     @memories = Memory.has_images.order("created_at DESC")
    #     @memories = @memories.in_decade(params[:decade]) if (params[:decade] && params[:decade].to_i > 0)
    #     @memories = @memories.in_category(params[:category]) if (params[:category])
    #     @memories = @memories.page(params[:page]).per(CONFIG[:custom_per_page])
    
    
    #I am making some testing for speed up this Sh#%
    if params[:decade] && params[:decade].to_i > 0 && params[:category]
      @memories = @all_memories.in_decade(params[:decade]).in_category(params[:category]).page(params[:page]).per(CONFIG[:custom_per_page])
    elsif params[:decade] && params[:decade].to_i > 0
      @memories = @all_memories.in_decade(params[:decade]).page(params[:page]).per(CONFIG[:custom_per_page])
    elsif params[:category]
      @memories = @all_memories.in_category(params[:category])#.page(params[:page]).per(CONFIG[:custom_per_page])

      # @memories = @all_memories.in_category(params[:category])#.page(params[:page]).per(CONFIG[:custom_per_page])
      if @memories.length < 120 
        memories = @memories + @all_memories.limit(100)
        @memories = Kaminari.paginate_array(memories).page(params[:page]).per(200)
      else
        @memories.page(params[:page]).per(CONFIG[:custom_per_page])
      end
      
    elsif !params[:decade].present? && !params[:category].present?
        @memories =  @all_memories.page(params[:page]).per(140)
    end
    
    
    
    # THIS IS THE PREVIOUS QUERY
    # @feeds =  Kaminari.paginate_array(@memories.reverse[1..5]).page(params[:feed]).per(5)
    
    
    # unless params[:current_tab]
    #   @current_tab = "home"
    # end
    
    # BIRTHYEAR IT'S OFF TEMPORARY (BY_BIRTHYEAR ON MEMORY CONTROLLER)
    # if session[:showbirthyearmemories] == true
    #       if !session[:sawbirthyearmemories].present?
    #         session[:sawbirthyearmemories] = true
    #         session[:showbirthyearmemories] = false
    #         birth_year = session[:birthyear].to_i
    #         @showbirthyearmemories = true
    #         #@birth_year_memories = Memory.similar_demographics(birth_year).order("created_at DESC").limit(3)
    #         
    #       else
    #         session[:sawbirthyearmemories] = true
    #       end
    #     end



    #Switching off since its not being used at now 
    # if user_signed_in?
    #   user_voted = current_user.votes.map(&:showdown_id)
    #   showdowns = !user_voted.empty? ? Showdown.next_vote(user_voted) : Showdown.scoped
    #   @showdowns = Kaminari.paginate_array(showdowns).page(params[:showdown]).per(1)
    # else
    #   showdowns = Showdown.scoped
    #   @showdowns = showdowns.page(params[:showdown]).per(1)
    # end
    
    
    # @memories_latest = Memory.latest.limit(CONFIG[:memories_per_page])
    # @memories_most_popular = Memory.most_popular.limit(CONFIG[:memories_per_page])    
    
    # if params[:sort] == "memories.views"
    #      @memories = @memories_most_popular
    #    else
    #      @memories = @memories_latest
    #    end
    
    
    respond_to do |format|
        format.html # index.html.erb
        format.js  { render :layout => false }
    end
  end
  
  def trending
    @memories = Memory.most_popular.order("created_at DESC").includes(:categories, :images).page(params[:page]).per(CONFIG[:memories_per_page])
    
    respond_to do |format|
        format.html { render :template => "home/index"}
        format.js  { render :layout => false, :template => "home/index" }
    end
  end
  
  def splash
    if params[:code]
      user_typed = params[:code].downcase
    end
    passwords = ["barbie", "lennon", "ewing", "popsicle", "lassie", "Saunders", "saunders", "vinyl"]
    if passwords.all?{ |p| passwords.include?(user_typed)} != true
      @visit = params[:visit] ||= Visit.new
      render :layout => false
    elsif passwords.all?{ |p| passwords.include?(user_typed)} == true
      cookies.delete :key
      cookies[:key] = {:value => 'invite', :expires => 30.days.from_now }
      #redirect_to :action => "entrance"
      redirect_to :action => "index"
    else
      @visit = params[:visit] ||= Visit.new
      render :layout => false
    end
  end
  
  # ONLY FOR TEST EMAILS NOTIFICATIONS TEMPLATE
  # def email_test
  #     @user = User.find(5).name
  #     @user_id = 5
  #     @other_user = User.find(156).name
  #     memory = Memory.last
  #     @image = memory.main_image
  #     @image_title = memory.name
  #     @link_text = "This is a nice link to something fun!"
  #     @link_url = "http://www.doyouremember.com"
  #     
  #     render :layout => "email"
  #   end
  
  def entrance
    #Getting the birthyear of non registered visitors
    if params[:ten] && params[:unid]
      birthyear = "19" + params[:ten] + params[:unid]
      session[:birthyear] = birthyear
      session[:showbirthyearmemories] = true
      redirect_to by_birthyear_url
    elsif params[:birthYear] == "skipped" #Skipping the birthyear of non registered visitors
      birthyear = "2012"
      session[:birthyear] = nil
      redirect_to :action => "index"
    else
      @categories = Category.with_memories
    
      unless params[:category]
        @selected_category = nil
        @memories = Memory.scoped.limit(18).order("created_at DESC")
      else
        @selected_category = Category.find(params[:category])
        @memories = Memory.in_category(params[:category]).limit(18).order("created_at DESC")
      end
    
      respond_to do |format|
        format.html{render :layout => false}
        format.js {render :layout => false}
      end
    end
  end

  #Browsing Memories by List
  def list_view
    @updown = params[:updown].nil? ? "DESC" : params[:updown]
    @v = @updown
    options_for_order = %w[name tag user_id follow comments_count created_at]
    if options_for_order.include?(params[:order])
      @memories = Memory.scoped.list_view(params[:order], @updown).page(params[:page]).per(CONFIG[:memories_per_page])
    else
      @memories = Memory.scoped.order("name ASC").page(params[:page]).per(CONFIG[:memories_per_page])
    end
  end
  
  #temporary location for put birthday info or login
  def birthyear
    render :layout => false
  end
  
  def vip
    cookies[:key] = {:value => 'invite', :expires => 30.days.from_now }
    params[:code] = "barbie"
    redirect_to splash_path(:code => "barbie")  
  end
  
  
  def routing_error
    @title = 'Unknown request (404)';
    @msg = 'I\'m sorry, but the page you requested could not be found.';
    render :error
  end
end

app/views/home/_birth_year_lightbox.html.haml
- if @showbirthyearmemories == true && @birth_year_memories.length >= 1
  :javascript
    Shadowbox.init({
        // let's skip the automatic setup because we don't have any
        // properly configured link elements on the page
        skipSetup: true
    });
    window.onload = function() {
        // open a welcome message as soon as the window loads
        Shadowbox.open({
            content:    "#{escape_javascript(render :partial => "home/birthyear")}",
            player:     "html",
            title:      "",
            height:     386,
            width:      802
        });
    };

app/views/home/_birthyear.html.haml
#birthYearScreen{:rel => "shadowbox"}
  -# .remove x
  #hereAreSomeMemories
    = image_tag "here-are-some-memories.png", :title => "Here are some memories we think you might enjoy"
  #birthYearMemories
    - @birth_year_memories.each do |bm|
      .birthYearhMemory{:class => cycle("left", "center", "right")}
        .bYMemory
          - if !bm.user_images.first.nil?
            = link_to image_tag(bm.user_images.first.this_url(:medium), :title => dyr_title(bm.name)), memory_path(bm)
          - else
            = link_to "This memory it's being updated or has no images available at this time", memory_path(bm)
        .bYdetailInfo
          .bYUser
            - if bm.is_anonymous
              Anonymous
            - else 
              = link_to bm.user.name, users_profile_path(bm.user.id), :class => "name med_grey small"
          .bYCategory
            - if bm.decade_name
              = link_to "#{truncate(bm.category.name.titleize, :length => 10)}", memories_per_category_path(bm.category.id)
              = link_to bm.decade_name, memories_per_decade_path(bm.decade)
            - else
              = link_to truncate(bm.category.name.titleize, :length => 15), memories_per_category_path(bm.category.id)
          .bYName
            = link_to dyr_title(truncate(bm.name, :length => 26)), memory_path(bm)
                        
    -# Something Here
  #loginMoreOptions
    Want to get more suggestions like these? 
    = link_to "Login", new_user_session_path
    or
    = link_to "Register", new_user_registration_path
    

app/views/home/_home_navigation.html.haml
%nav
  %ul
    %li.categoriesTab{:class => "#{"activeTab" if @current_tab == "category"}"}
      = link_to("#", :id => "choose_category", @current_tab => "category") do
        - if @current_tab == "category"
          .title.on CATEGORY
          - if  !@category.nil? && @category.name.to_s == "you may like"
            .description.on (select one)
          - else
            .description.on= (@category.nil? ? ' (select one)' : truncate(@category.name.titleize, :length => 25))
        - else
          .title CATEGORY
          - if  !@category.nil? && @category.name.to_s != "you may like"
            .description (select one)
          - else
            .description= (@category.nil? ? ' (select one)' : truncate(@category.name.titleize, :length => 25))
    %li.memoriesCounter{:class => "#{"activeTab" if params[:controller] == "home" || params[:sort] == "memories.created_at" }"}
      = link_to("#", :id => "view_latest") do
        - if params[:controller] == "home" || params[:sort] == "memories.created_at" 
          .title.on 
            ALL
            = number_with_delimiter(Memory.count)
          .description.on memories
        - else
          .title 
            ALL
            = number_with_delimiter(Memory.count)
          .description memories

    %li.trendingMemoriesTab{:class => "#{"activeTab" if params[:sort] == "memories.views"}"}
      = link_to("#", :id => 'view_most_popular') do
        - if params[:sort] == "memories.views"
          .title.on TRENDING
          .description.on memories
        - else
          .title TRENDING
          .description memories
      / - if params[:controller] == "home"
      /           = link_to("#", :id => 'view_most_popular', @current_tab => "suggested") do
      /             .title TRENDING
      /             .description memories
      /         - else 
      /           = link_to(root_path, :id => "view_most_popular", @current_tab => "home") do
      /             .title TRENDING
      /             .description memories
    %li.doYouRememberLogo
      #doYouRememberTextLogo
        = link_to image_tag("#{asset_path "do-you-remember-text-logo2.png"}", :title => "Do You Remember", :alt => "Do You Remember"), root_path
    %li.memoryBank
      - if user_signed_in? == true
        = link_to(memory_bank_path) do
          - if params[:controller] == "users"
            .title.on MEMORY BANK
            .description.on your saved memories
          - else
            .title MEMORY BANK
            .description your saved memories
      - else
        = link_to(memory_bank_path) do
          .title.dark MEMORY BANK
          .description.dark login to access
    %li.last{:class => "#{"activeTab" if @current_tab == "suggested"}"}
      - if user_signed_in? == true
        = link_to(memories_per_similar_demographics_path) do
          - if @current_tab == "suggested"
            .title.on SUGGESTED
            .description.on just for you
          - else
            .title SUGGESTED
            .description just for you
      - else
        = link_to(new_user_session_path) do
          .title.dark SUGGESTED
          .description.dark login to access
= render :partial => 'shared/categories_and_decades'

app/views/home/_more_sidebar.haml
#about.side_button
  =link_to 'About&nbsp;&raquo;'.html_safe, about_path 
#terms_of_service.side_button
  =link_to 'Terms of Service&nbsp;&raquo;'.html_safe, terms_of_service_path 
#privacy_policy.side_button
  =link_to 'Privacy&nbsp;&raquo;'.html_safe, privacy_policy_path 
#contact_us.side_button
  =link_to 'Contact Us&nbsp;&raquo;'.html_safe, contact_us_path 
#help.side_button
  =link_to 'Help&nbsp;&raquo;'.html_safe, help_path 
#blog.side_button
  =link_to 'Blog&nbsp;&raquo;'.html_safe, 'http://blog.doyouremember.com'
#get_the_app.side_button
  =link_to 'Get the App&nbsp;&raquo;'.html_safe, get_our_app_path 

/ add some code to check which page is the current page, and if so, add a .current class,
/ which highlights the sidebar item in some way.

app/views/home/about.haml
.site_info
  #sidebar
    =render"more_sidebar"
  #content
    %h1 About Us
    DoYouRemember is the first social website based on nostalgia. Our goal is to bring people together by connecting them through their memories. DoYouRemember lets you create and share your memories with a nostalgic community. People use DoYouRemember to bridge their past with friends, family, and the world.
    %h3 Submission Rules
    %ul.submissions
      %li DoYouRemember is all about our love for nostalgia. All submissions , including images, videos,  descriptions, titles and comments, should relate to topics regarding the past.
      %li DoYouRemember supports our friends who earn their livings through buying or selling products or services relating to all that’s retro. You may post a memory that’s commercial in nature, however, you may not include a phone number, address, URL or link within images, descriptions, videos, descriptions, titles and comments. You may activate the link to your website, which is found below the memory description field.
      %li You may not post more than ten (10) memories that are commercial in nature, within a given hour. 
      %li All content must be in good taste. 
      %li Failure to comply with any of these Rules may result in your submission being flagged. A user that is flagged three times will be suspended from DoYouRemember for 30 days. Further non-compliance may result in permanent revocation of user privileges. 
    For more information, see our #{link_to 'Terms of Service Agreement', terms_of_service_path}.

app/views/home/birthyear.html.haml
!!! 5

/[if lt IE 7] <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en">
/[if IE 7] <html class="no-js lt-ie9 lt-ie8" lang="en">
/[if IE 8] <html class="no-js lt-ie9" lang="en">
/ [if gt IE 8]<!
%html.no-js{:lang => "en"}
  / <![endif]
  %head
    %meta{:charset => "utf-8"}
    %meta{:content => "IE=edge,chrome=1", "http-equiv" => "X-UA-Compatible"}
    %title DoYouRemember?
    %meta{:content => "", :name => "description"}
    %meta{:content => "width=device-width", :name => "viewport"}
    %link{:href => "css/style.css", :rel => "stylesheet"}
    = stylesheet_link_tag "birthyear"
    %script{:src => "js/libs/modernizr-2.5.3.min.js"}
    = csrf_meta_tags
  %body
    /[if lt IE 7] <p class=chromeframe>Your browser is <em>ancient!</em> <a href="http://browsehappy.com/">Upgrade to a different browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to experience this site.</p>
    #container
      #birthYearForm
        %h1
          = link_to "LOGIN", new_user_session_path
          %br/
          \or
          %br/
          Enter your birth year below.
        .birthyearForm
          = form_tag('/entrance', :method => :put, :id => "birthYear") do
            = text_field_tag '1', nil, :in => 1..1, :value => 1, :disabled => true
            = text_field_tag '9', nil, :in => 9...9, :value => 9, :disabled => true
            = text_field_tag 'ten', nil, :in => 1...9, :placeholder => "Y", :size => 1, :maxlength => 1
            = text_field_tag 'unid', nil, :in => 0...1, :placeholder => "Y", :size => 1, :maxlength => 1
            =# select_year(00, :start_year => 99, :end_year => 2000)
            = submit_tag "Enter", :title => "Input your birth year", :id => "getIn"
          = link_to "Skip", entrance_path(:birthYear => "skipped"), :id => "skipBirthYear"
  
        
              
    = javascript_include_tag 'http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js'
    = javascript_include_tag 'http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.18/jquery-ui.min.js'
    = javascript_include_tag "silvester", "transformie"
    = javascript_include_tag "tooltip", "jquery.numeric", "entrance", "application"
    - if Rails.env.eql?('production')
      :javascript
        window.jQuery || document.write('<\/script>')
        var _gaq=[['_setAccount','UA-31381947-1'],['_trackPageview']];
        (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
        g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
        s.parentNode.insertBefore(g,s)}(document,'script'));

app/views/home/contact_us.haml
.site_info
  #sidebar
    =render"more_sidebar"
  #content
    %h1 Contact Us
    %p For ongoing information about DoYouRemember, please read our #{link_to 'company blog', "http://blog.doyouremember.com" } or follow us on Twitter at #{link_to '@doyouremember', 'http://twitter.com/doyouremember' }.
    %p Also, feel free to contact us with service questions, partnership proposals, or media inquiries to #{mail_to 'info@doyouremember.com'}.

app/views/home/email_test.haml
Dear #{@user},
%br
#{@other_user} just #{@event}.
%br
%br
#{link_to(@link_text, @link_url)}

app/views/home/entrance.html.haml
!!! 5

/[if lt IE 7] <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en">
/[if IE 7] <html class="no-js lt-ie9 lt-ie8" lang="en">
/[if IE 8] <html class="no-js lt-ie9" lang="en">
/ [if gt IE 8]<!
%html.no-js{:lang => "en"}
  / <![endif]
  %head
    %meta{:charset => "utf-8"}
    %meta{:content => "IE=edge,chrome=1", "http-equiv" => "X-UA-Compatible"}
    %title DoYouRemember?
    %meta{:content => "", :name => "description"}
    %meta{:content => "width=device-width", :name => "viewport"}
    %link{:href => "css/style.css", :rel => "stylesheet"}
    = stylesheet_link_tag "entrance"
    %script{:src => "js/libs/modernizr-2.5.3.min.js"}
    = csrf_meta_tags
  %body
    /[if lt IE 7] <p class=chromeframe>Your browser is <em>ancient!</em> <a href="http://browsehappy.com/">Upgrade to a different browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to experience this site.</p>
    #container
      %nav
        %ul
          %li{:id => "ALL", :class => "#{"span" unless params[:category].present? }"}= link_to "All Categories", entrance_path, :remote => true
          - @categories[0..20].each do |c|
            %li{:id => c.id, :class => "#{"span" if params[:category] == c.to_param}"}= link_to c.name.titleize, entrance_path(:category => c)#, :remote => true
      %article
        = render :partial => 'login_box'

        #latestMemories
          = render :partial => 'latest_memories'

              
    = javascript_include_tag 'http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js'
    = javascript_include_tag 'http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.18/jquery-ui.min.js'
    = javascript_include_tag "silvester", "transformie"
    = javascript_include_tag "tooltip", "jquery.numeric", "entrance", "application"
    - if Rails.env.eql?('development')
      :javascript
        window.jQuery || document.write('<\/script>')
        var _gaq=[['_setAccount','UA-31381947-1'],['_trackPageview']];
        (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
        g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
        s.parentNode.insertBefore(g,s)}(document,'script'));

app/views/home/entrance.js.erb
<% if @selected_category == nil %>
	$('li.span').removeClass('span');
	$("#ALL").addClass('span');
	$('#latestMemories').html("<%= escape_javascript(render :partial => 'latest_memories') %>");
<% else %>
	$('li.span').removeClass('span');
	$("#<%= @selected_category.id %>").addClass('span');
	$('#latestMemories').html("<%= escape_javascript(render :partial => 'latest_memories') %>");
<% end %>

app/views/home/error.haml
.content_divs
  .content_div
    .empty
      %h2.title.light_yellow= @title 
      .cont.pages= @msg

app/views/home/get_our_app.haml
.site_info
  #sidebar
    = render "more_sidebar"
  #content
    = image_tag 'app_store.png'

app/views/home/login_register.haml
.register_login_box
  .register_box
    %span Please Sign Up through Facebook to continue...
    %a{:href => "/auth/facebook"}
      = image_tag asset_path 'register_big.png', :alt => "Facebook", :title => 'Facebook', :border => 0, :size => "146x28"

    %a.nothanks{:href => "/"}
      No thanks, I'll just browse for now
  
  .login_buttons
    %span
      Already signed up?
    %a{:href => "/auth/facebook", :class => "social_button_m"}
      = image_tag asset_path 'login_m_f.png', :alt => "Facebook", :title => 'Facebook', :border => 0, :size => "146x28"


    %a{:href => "/auth/twitter", :class => "social_button_m"}
      = image_tag asset_path 'login_m_t.png', :alt => "Twitter", :title => 'Twitter', :border => 0, :size => "146x28"