config/routes.rb
Dyr::Application.routes.draw do
  
  get "conform/index"

  resources :posts
  if Rails.env.staging? || Rails.env.development?
    controller :mobile_api do
      
      get "addcoments"
      get "addfavourite"
      get "addmemoriedetails"
      get "B"
      get "GetMemories"
      get "comments"
      get "followuser"
      get "getcategories"
      get "getcomments"
      get "getshowdown"
      get "getuserdetails"
      get "rememberedmemories"
      get "result"
      get "search"
      get "signin"
      get "views"
      get "usercomments"
      get "userfollowedby"
      get "userfollowing"
      get "userrememberedmemories"
      get "emailconform"
      get "index"
      get "conform"
      post "conform"
    end
  end
  
  get "banned/index"
  get "whotofollow/index"

  get "images/destroy"
  get "list/index"

  controller :feeds do
    get "feeds/index"
    get "feeds/next"
    
  end

  resources :categories
  
  resources :votes
  
  resources :visits, :only => :create, :method => :post

  root :to => "home#index"
  controller :home do
    match 'list_view', :via => [:get, :post], :path => "/listing-memories"
    match 'vip', :via => :get, :path => '/VIP_ENTRANCE'
    match 'vip', :via => :get, :path => '/VIP_entrance'
    match 'vip', :via => :get, :path => '/vip_ENTRANCE'
    match 'vip', :via => :get, :path => '/vip_entrance'
    match 'vip', :via => :get, :path => '/preview'
    match 'decade_index', :via => :get
    match 'entrance', :via => [:get, :put]
    match 'birthyear', :via => [:get, :put]
    match 'splash'
    match 'help'
    match 'about'
    match 'terms_of_service'
    match 'privacy_policy'
    match 'get_our_app'
    match 'login_register'
    match 'trending'
    match 'contact_us'
  end
  
  resources :showdowns
  match "/voting/next_vote" => "showdowns#next_vote", :via => :get
  
  
  devise_for :images, :controllers => { :images => "images", :memories => "memories" }, :sign_out_via => [:post, :delete, :get]
  namespace :images do
    match 'edit/:id', :action => :edit, :as => 'edit_images'
    match ':memory_id/:id', :action => :destroy, :as => 'delete_by_images_memory_id'
  end

  devise_for :users, :controllers => { :registrations => "registrations", :passwords => 'passwords', :sessions => 'sessions', :confirmations => "confirmations"}, :sign_out_via => [:post, :delete, :get]
  namespace :users do
    post 'follow'
    match 'unfollow/:followee_id', :action => :unfollow, :as => 'unfollow'
    match 'home'
    match ':id/profile', :action => :profile, :as => 'profile'    
    match 'follow_from_profile/:followee_id', :action => :follow_from_profile, :as => 'follow_from_profile'
    match 'unfollow_from_profile/:followee_id', :action => :unfollow_from_profile, :as => 'unfollow_from_profile'
    match 'follow_from_profile_followers/:followee_id', :action => :follow_from_profile_followers, :as => 'follow_from_profile_followers'
    match 'unfollow_from_profile_followers/:followee_id', :action => :unfollow_from_profile_followers, :as => 'unfollow_from_profile_followers'
    match 'bu/:id', :action => 'become_user', :as => 'b' #convenience method to circumvent FB logins, should never be called by the public
    match 'set_notification/:notification_bit/:new_state', :action => :set_notification, :as => :set_notification
    match 'set_preference/:notification_bit/:new_state', :action => :set_preference, :as => :set_preference
  end
  
  match '/auth/:service/callback' => 'services#create' 
  resources :services, :only => [:index, :create, :destroy]
  
  match '/memories/add-to-memory-bank' => 'memories#add_to_memory_bank', :as => 'add_to_memory_bank'
  match '/memories/my-memory-bank' => 'memories#memory_bank', :as => 'memory_bank'
  match '/memories/:id/send_to_a_friend' => 'memories#send_to_a_friend', :as => 'send_to_a_friend'
  match '/memories/categories/:category_id' => 'memories#per_category', :as => 'memories_per_category'
  match '/memories/decades/:decade_id' => 'memories#per_decade', :as => 'memories_per_decade'
  match '/memories/my-suggested-memories' => 'memories#per_similar_demographics', :as => 'memories_per_similar_demographics'
  match '/memories/birthyear-suggested-memories' => 'memories#by_birthyear', :as => 'by_birthyear'
  resources :memories do
    member do
      match 'also_remembers'
      match 'forgot'
      match 'suspend'
      match 'unsuspend'
      match 'ban_user'
      match 'unban_user'
    end
  end
  
  resources :previews, :only => [] do
    member do
      get 'comments'
      get 'related'
      get 'remembered'
      get 'photos'
      get 'post_comment'
      get 'also_remembers'
      get 'forgot'
      get 'follow'
      get 'unfollow'
      get 'delete'
    end
  end
  
  resources :images, :only => [:create, :update, :destroy]
  
  match '/search' => 'search#new'
  match '/search/result' => 'search#result'
  match '/whotofollow/index' => 'whotofollow#index'
  match '/images/memory_id/id' => 'images/:memory_id#:id'

  resources :comments, :only => :create
 
  namespace :v1 do
    controller :lists do
      match 'categories'
      match 'decades'
    end
    controller :memories do
      match 'memories/:start/:amount', :action => :index
      match 'memories/:start/:amount/decade/:id', :action => :per_decade
      match 'memories/:start/:amount/category/:id', :action => :per_category
      match 'memories/:start/:amount/suggested/:year/:gender', :action => :suggested
      match 'memories/:start/:amount/suggested/:year', :action => :suggested
    end
  end
  
  resources :invitations, :only => [:new, :create]











end

app/models/whotofollow.rb
class Whotofollow
  attr_accessor :params, :results, :term_filtered

  STOP_WORDS = %w(a an the and or some of for in I)
  COLUMNS = %w(users.first_name) # users.description images.caption

  def initialize(params = {}, page = 1)
    @params = params
    @keyword_array = @params[:term].gsub(/[^\w\s]/,'').split(' ').reject{|word| STOP_WORDS.include?(word)}
    @term_filtered = @keyword_array.join(' ')
    @unordered = build_query(page)
    @results = @unordered
  end

  def reorder(params ={})
    @results = @unordered.order('users.' + params[:sort] + ' ' + params[:direction])
  end

  private
  def build_query(page)
    #init = 'User.includes(:images)'
    init = 'User'
    arel = init

   arel += find(:all, :conditions => ["first_name LIKE ?", "%#{session[:search]}%"], :order => "first_name ASC")
    eval(arel).page(page)
  end

end

app/controllers/whotofollow_controller.rb
class WhotofollowController < ApplicationController
  def index

    if request.method.eql?('POST')
      session[:search] = nil
      session[:search] = params[:search]
      @users = User.where("first_name LIKE ? OR last_name LIKE ?","%#{session[:search]}%", "%#{session[:search]}%")
    else
      @users = User.where('id != ?', current_user.id)
    end

  end

  private
  def sort_column
    User.column_names.include?(params[:sort]) ? params[:sort] : "first_name"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

  def follow
    assign_follows(params[:followee_id])
    render :layout => false
  end
end

app/views/whotofollow/index.html.haml
#wrapper_content
  #main_content
    .memory
      .cont
        .content_box.long
          %h2{:style => "text-align:center; font-size:26px;"} Who To Follow
          %table.list{:cellpadding => "5", :cellspacings => "4", :colspan => "0", :width => "100%"}
            %tr.line_bottom
              %td{:colspan => "2", :valign => "middle"}
                #search_memories
                  = form_tag whotofollow_index_path do
                    = text_field_tag 'search', '', :placeholder => 'SEARCH who to follow', :maxlength => 60, :spellcheck => true
                    =# image_tag("searchMemoryButton.png"), :title => "title", :class => "class"
                    = image_submit_tag "searchMemoryButton.png", :id => 'search_btn'
              %td.line_left_right{:valign => "middle", :width => "90"}
                %label Age
              %td{:colspan => "3", :valign => "middle", :width => "90"}
                %label Posts
            -if @users.count > 0
              -@users.each do |eachusers|
                %tr
                  %td{:valign => "middle", :width => "100"}
                    %a{:href => users_profile_path(eachusers)}
                      = image_tag eachusers.my_profile_image, :size => '50x50'
                  %td{:valign => "middle", :width => "160"}
                    %a{:href => users_profile_path(eachusers)}
                      = eachusers.name
                  %td.line_left_right{:valign => "middle", :width => "90"}
                    %label
                      // this breaks if your age is not in the system -- User should have an age method
                      //= Date.today.year - eachusers.birth_year
                  %td{:valign => "middle", :width => "90"}
                    %label
                      = eachusers.public_memories.count
                      -#= Memory.count_memoryby_userid(eachusers.id)
                  %td{:valign => "middle", :width => "300"}
                    -@memories = Memory.scoped.has_images.where('user_id = ?', eachusers.id).all(:limit => "3")
                    = render :partial => "memories/post_preview_whotofollow", :collection => @memories, :as => :m
                  %td{:valign => "middle"}
                    - whotofollow = current_user.followees.where('followee_id <> ?', eachusers.id)
                    .profile_following
                      .col1
                        -if whotofollow.count>0
                          %a{:href => users_unfollow_from_profile_path(eachusers), 'data-remote' => true, :class => "following_#{eachusers.id}"}
                            .z.orange.small
                              unfollow
                        -else
                          %a{:href => users_follow_from_profile_path(eachusers), 'data-remote' => true, :class => "not-following_#{eachusers.id}"}
                            .btn.yellow.small
                              follow
            -else
              %tr
                %td{:colspan => "5", :valign => "middle", :width => "100%"}
                  = 'There is no user exist!'